version: '3.8'

services:

  web:
    build: .
    env_file:
      - .env.prod
    container_name: web
    restart: always
    command: ["./docker/app.sh"]
    ports:
      - "8000:8000"
    extra_hosts:
      - "host.docker.internal:host-gateway"